### ISSUE TITLE
✨ Display current GPS coordinates

### ISSUE THREAD

**Issue by elfingar** [ecatch-kyst/web#50] opened 2019-02-25 16:36 UTC
## Expected Behavior

The user should be able to real-time see his coordinates in the application

- [x] Fetch the GPS location from the device
- [ ] Display this information in a good way 
- [ ] Write tests

## Priority

Medium

## Size

1-2

**Comment by balazsorban44** [comment] 2019-03-09 15:02
This is kind of a duplicate of #52. Track this issue there. :lock:

**Closed as completed by balazsorban44** 2019-03-09 15:02 UTC
Labels: duplicate, feature, wontfix
